### ISSUE TITLE
Issue: Simplify Agent Explanations Output in Leftcurve Plugin

### ISSUE THREAD

**Issue by sBaki92** [lftcrv/trading-agent-snak#18]
### Description
Currently, when the agent retrieves previous explanations using the `get_agent_explanations` tool, it logs detailed information with many fields showing "N/A" values:

```
Explanation #1 (5 hours ago):
Market: N/A
Reason: N/A
Analysis:
  Price: N/A
  Volume: N/A
  Volatility: N/A
  Trend: N/A
Decision Type: N/A
Explanation: Following my quantitative framework, I've maintained positions...
```

These "N/A" values can be distracting and may negatively impact the agent's decision-making process by providing noisy, empty data.

### Expected Behavior
The output should be simplified to only show the explanation text and timestamp (time ago), hiding all fields with "N/A" values:

```
Explanation #1 (5 hours ago):
Following my quantitative framework, I've maintained positions despite strong trending conditions...
```

### Proposed Solution
Modify the `getAgentExplanations` function in `plugins/leftcurve/src/actions/paradexActions/getExplanations.ts` to:

1. Only log fields that have actual values (not null/undefined/N/A)
2. Alternatively, simplify the output entirely to just show the explanation text and timestamp

### Technical Details
The issue occurs in the logging section around line 70-80 in `getExplanations.ts` where all fields are output regardless of whether they contain meaningful values.

### Impact
This change would:
- Provide cleaner, more focused output for the agent
- Reduce potential confusion in the agent's reasoning
- Improve the quality of agent decisions by focusing on the core explanations

### Additional Notes
The database schema and structure can remain unchanged - this is purely a display/output issue in the logging functionality.
